first =input ('Input Your First Number :')
second =input ('Input Your Second Number :')
third =input ('Input Your third Number :')
fourth =input ('Input Your fourth Number :')
fifth =input ('Input Your fifth Number :')
print('float of %s '%first+' Equal %s ' %float(first))
print('Complex of %s '%first+' Equal %s ' %complex(first))
print('float of %s '%second+' Equal %s ' %float(second))
print('Complex of %s '%second+' Equal %s ' %complex(second))
print('float of %s '%third+' Equal %s ' %float(third))
print('Complex of %s '%third+' Equal %s ' %complex(third))
print('float of %s '%fourth+' Equal %s ' %float(fourth))
print('Complex of %s '%fourth+' Equal %s ' %complex(fourth))
print('float of %s '%fifth+' Equal %s ' %float(fifth))
print('Complex of %s '%fifth+' Equal %s ' %complex(fifth))